class Actions:
    """
    Args
    """
    principal_list = "principal-list"
    common_info = "common-info"
    principal_update = "principal-update"
    custom_field_update = "custom-field-update"
    acl_field_update = "acl-field-update"
    group_membership_update = "group-membership-update"
    report_bulk_users = "report-bulk-users"
    sco_expanded_contents = "sco-expanded-contents"
    permissions_info = "permissions-info"
    sco_shortcuts = "sco-shortcuts"
    logout = "logout"
    login = "login"
    sco_update = "sco-update"
    permissions_update = "permissions-update"
    report_quiz_interactions = "report-quiz-interactions"
    report_bulk_consolidated_transactions = "report-bulk-consolidated-transactions"
    meeting_feature_update = "meeting-feature-update"
    meeting_feature_info = "meeting-feature-info"
    acl_field_list = "acl-field-list"
    custom_fields_delete = "custom-fields-delete"
    custom_fields = "custom-fields"
    sco_delete = "sco-delete"
    principals_delete = "principals-delete"